import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GameContextProvider from "./context/gameContext";
import ThemeProvider from "./context/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rock Paper Scissor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel='icon' href='/favicon.ico' />
            </head>
      <body className={inter.className}>
        <GameContextProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </GameContextProvider>
      </body>
    </html>
  );
}
